import { useEffect, useState } from 'react'
import type { CSSProperties } from 'react'
import { staffApi } from '../../api/client'
import { useStaffAuth } from '../../auth/StaffAuthContext'

/**
 * SECTION 188 (2026-10-02) "now we work on Ledger master ... create Ledger master ... for 3 pages
 * Jobcard, Material Transfer, RepairBill ... only 4 types in dropdown Company, Dealer, Party,
 * Insurance ... company and dealer fetch from Erp which already we fetch ... work on Party and
 * Insurance ... dont want Gender, Occupation, DOB ... Created By/Created DateTime/Updated By/
 * Updated DateTime dont show on ui ... this ui make responsive attractive".
 *
 * Confirmed via AskUserQuestion:
 *  - This page only creates/edits "Party" and "Insurance" rows (LedgerMasterController.cs/
 *    Models/LedgerMaster.cs). "Company" and "Dealer" are shown as disabled options with a
 *    "Coming soon" note - still pinning down the exact ERP (baplfinal) table/API to read them from
 *    with you, not guessed at here.
 *  - Ledger Code is auto-generated by the backend (Prefix Master "ledger-master" module) - not an
 *    input field here at all, shown read-only after creation.
 *  - Gender/Occupation/DOB are not fields on this form at all (dropped, not just hidden).
 *  - Created By/Created DateTime/Updated By/Updated DateTime are intentionally NOT shown here, and
 *    City/State are skipped entirely - CONFIRMED AGAIN via AskUserQuestion in SECTION 189 below,
 *    even after you shared the DMS reference screenshot showing those columns on the real system.
 *
 * SECTION 189 (2026-10-02) "same ui give like which i give code of dms" - your screenshot of the
 * real DMS Customer Ledger page. Confirmed via AskUserQuestion:
 *  - Per-dealer scoping added (DealerId on every row - see LedgerMaster.cs/LedgerMasterController.cs).
 *    CorporateAdmin/SystemAdmin see a Dealer filter dropdown + Dealer column (sourced from the
 *    existing GET /api/dashboard/corporate/filters endpoint - reused rather than inventing a new
 *    one) and must pick a dealer when adding a ledger; every other role never sees either - they're
 *    always scoped to their own dealer server-side.
 *  - Toolbar restyled toward the screenshot's layout (Dealer + Ledger Type selects on the left,
 *    Add/Export/Search on the right) - but City/State/Created Date/Updated Date columns stay OFF,
 *    per your explicit re-confirmation, so this is the toolbar/chrome only, not full column parity.
 *  - Added a CSV export button (the screenshot's green Excel icon) - a scoped-down version: this
 *    app has no Excel-generation service wired up for this feature yet, so this exports a plain
 *    .csv (opens fine in Excel) of every row matching the current filters, not a styled .xlsx -
 *    flagging this as an assumption/interpretation of "export," not a confirmed requirement.
 */

type LedgerType = 'Company' | 'Dealer' | 'Party' | 'Insurance'
const LOCAL_LEDGER_TYPES: LedgerType[] = ['Party', 'Insurance']
const ALL_LEDGER_TYPES: LedgerType[] = ['Company', 'Dealer', 'Party', 'Insurance']
const ERP_SOURCED_TYPES: LedgerType[] = ['Company', 'Dealer']
const ORG_WIDE_ROLES = ['CorporateAdmin', 'SystemAdmin']

interface DealerOption {
  id: string
  name: string
}

interface LedgerRow {
  id: string
  dealerId: string
  dealerName: string | null
  ledgerType: string
  ledgerCode: string
  ledgerName: string
  mobileNumber: string | null
  alternateMobileNo: string | null
  eMail: string | null
  address: string | null
  pin: string | null
  gstno: string | null
  pan: string | null
  aadharNumber: string | null
  isActive: boolean
}

interface LedgerFormState {
  ledgerType: LedgerType
  dealerId: string
  ledgerName: string
  mobileNumber: string
  alternateMobileNo: string
  eMail: string
  address: string
  pin: string
  gstno: string
  pan: string
  aadharNumber: string
}

const EMPTY_FORM: LedgerFormState = {
  ledgerType: 'Party',
  dealerId: '',
  ledgerName: '',
  mobileNumber: '',
  alternateMobileNo: '',
  eMail: '',
  address: '',
  pin: '',
  gstno: '',
  pan: '',
  aadharNumber: '',
}

const PAGE_SIZE = 10
const EXPORT_MAX_ROWS = 5000

const PAGE_TITLE_STYLE: CSSProperties = { fontSize: 22, fontWeight: 700, letterSpacing: '-0.01em', color: '#111827', margin: 0 }
const PAGE_SUBTITLE_STYLE: CSSProperties = { fontSize: 14, color: '#6b7280', margin: '4px 0 0' }
const SECTION_TITLE_STYLE: CSSProperties = { fontSize: 16, fontWeight: 600, color: '#111827', letterSpacing: '-0.005em', marginTop: 0 }
const TH_STYLE: CSSProperties = { fontSize: 11, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.05em', color: '#6b7280', textAlign: 'left' }

const TYPE_BADGE_COLORS: Record<string, { bg: string; fg: string }> = {
  Party: { bg: '#eef2ff', fg: '#4338ca' },
  Insurance: { bg: '#ecfdf5', fg: '#047857' },
  Company: { bg: '#fffbeb', fg: '#b45309' },
  Dealer: { bg: '#fef2f2', fg: '#b91c1c' },
}

function TypeBadge({ type }: { type: string }) {
  const c = TYPE_BADGE_COLORS[type] ?? { bg: '#f3f4f6', fg: '#374151' }
  return (
    <span style={{ display: 'inline-block', background: c.bg, color: c.fg, fontSize: 11, fontWeight: 700, padding: '3px 10px', borderRadius: 999, letterSpacing: '0.02em' }}>
      {type.toUpperCase()}
    </span>
  )
}

// CSV cell quoting - wraps in quotes and escapes embedded quotes only when actually needed, so a
// plain value stays readable un-quoted.
function csvCell(value: string | null | undefined): string {
  const v = value ?? ''
  return /[",\n]/.test(v) ? `"${v.replace(/"/g, '""')}"` : v
}

// Scoped stylesheet - same pattern as AttendancePage.tsx's ATTENDANCE_STYLES: keeps this page's
// extra responsiveness/attractiveness local without touching any shared/global CSS file I haven't
// seen. Below LEDGER_BREAKPOINT the table collapses into a stacked card per row (plain CSS, no JS
// breakpoint state) so the page stays usable on a phone-width screen.
const LEDGER_BREAKPOINT = 760
const LEDGER_STYLES = `
  .ledger-filters-row { display: flex; gap: 16px; flex-wrap: wrap; align-items: flex-end; margin-bottom: 14px; }
  .ledger-filter-field { display: flex; flex-direction: column; gap: 4px; }
  .ledger-filter-field label { font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.04em; color: #6b7280; }
  .ledger-filter-field select { min-width: 200px; }
  .ledger-actions-row { display: flex; gap: 10px; flex-wrap: wrap; align-items: center; margin-bottom: 14px; justify-content: space-between; }
  .ledger-type-tabs { display: flex; gap: 6px; flex-wrap: wrap; }
  .ledger-type-tab {
    padding: 6px 14px; border-radius: 20px; border: 1px solid #e5e7eb; background: #fff;
    font-size: 13px; font-weight: 600; color: #374151; cursor: pointer; white-space: nowrap;
  }
  .ledger-type-tab.active { background: #111827; color: #fff; border-color: #111827; }
  .ledger-type-tab.disabled { cursor: not-allowed; opacity: 0.55; }
  .ledger-toolbar-right { display: flex; gap: 10px; flex-wrap: wrap; align-items: center; }
  .ledger-search { min-width: 180px; max-width: 320px; }
  .ledger-table-wrap { overflow-x: auto; border: 1px solid #e5e7eb; border-radius: 10px; }
  .ledger-table { width: 100%; border-collapse: collapse; font-size: 13px; }
  .ledger-table th { text-align: left; padding: 10px 14px; background: #f8fafc; font-weight: 600; color: #475569; border-bottom: 1px solid #e5e7eb; white-space: nowrap; }
  .ledger-table td { padding: 8px 14px; border-bottom: 1px solid #f1f5f9; vertical-align: middle; }
  .ledger-table tbody tr:last-child td { border-bottom: none; }
  .ledger-table tbody tr:hover { background: #f8fafc; }
  .ledger-form-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(190px, 1fr)); gap: 12px; }
  .ledger-form-grid label { display: block; font-size: 12px; color: #6b7280; margin-bottom: 4px; }
  .ledger-form-grid input, .ledger-form-grid select { width: 100%; box-sizing: border-box; }
  .ledger-pagination { display: flex; gap: 10px; align-items: center; justify-content: flex-end; margin-top: 12px; font-size: 13px; color: #6b7280; }
  .ledger-coming-soon { font-size: 13px; color: #92400e; background: #fffbeb; border: 1px solid #fde68a; border-radius: 8px; padding: 10px 14px; margin-bottom: 14px; }
  .ledger-export-btn {
    display: inline-flex; align-items: center; justify-content: center; width: 34px; height: 34px;
    border-radius: 8px; border: 1px solid #16a34a; background: #ecfdf5; color: #16a34a; cursor: pointer; font-size: 15px;
  }
  .ledger-export-btn:disabled { opacity: 0.5; cursor: not-allowed; }

  @media (max-width: ${LEDGER_BREAKPOINT}px) {
    .ledger-table thead { display: none; }
    .ledger-table, .ledger-table tbody, .ledger-table tr, .ledger-table td { display: block; width: 100%; }
    .ledger-table tr { border-bottom: 1px solid #e5e7eb; padding: 10px 14px; }
    .ledger-table td { border-bottom: none; padding: 3px 0; }
    .ledger-table td[data-label]::before { content: attr(data-label); display: block; font-size: 10px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.04em; color: #9ca3af; }
    .ledger-actions-row { flex-direction: column; align-items: stretch; }
    .ledger-toolbar-right { justify-content: stretch; }
    .ledger-search { max-width: none; flex: 1; }
  }
`

export function LedgerMasterPage() {
  const { profile } = useStaffAuth()
  const isOrgWide = !!profile && ORG_WIDE_ROLES.includes(profile.role)

  const [rows, setRows] = useState<LedgerRow[]>([])
  const [totalRecords, setTotalRecords] = useState(0)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  const [dealers, setDealers] = useState<DealerOption[]>([])
  const [dealerFilter, setDealerFilter] = useState('')
  const [typeFilter, setTypeFilter] = useState<LedgerType | ''>('')
  const [search, setSearch] = useState('')
  const [pageIndex, setPageIndex] = useState(0)

  const [showForm, setShowForm] = useState(false)
  const [editId, setEditId] = useState<string | null>(null)
  const [form, setForm] = useState<LedgerFormState>(EMPTY_FORM)
  const [saving, setSaving] = useState(false)
  const [formError, setFormError] = useState<string | null>(null)
  const [mobileWarning, setMobileWarning] = useState<string | null>(null)
  const [exporting, setExporting] = useState(false)

  // SECTION 189 - reuses the EXISTING /api/dashboard/corporate/filters endpoint for the Dealer
  // dropdown's {id, name} list, rather than adding a new one - only called for org-wide roles
  // (every other role never sees this dropdown, and the endpoint itself is CorporateAdmin/
  // SystemAdmin-gated anyway).
  useEffect(() => {
    if (!isOrgWide) return
    staffApi
      .get<{ dealers: DealerOption[] }>('/api/dashboard/corporate/filters')
      .then((res) => setDealers(res.data.dealers))
      .catch(() => {
        /* best-effort - the Dealer filter/field just stays empty if this fails */
      })
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isOrgWide])

  const load = () => {
    setLoading(true)
    setError(null)
    staffApi
      .get<{ data: LedgerRow[]; totalRecords: number }>('/api/ledger-master', {
        params: {
          searchTerm: search || undefined,
          pageIndex,
          pageSize: PAGE_SIZE,
          ledgerType: typeFilter && LOCAL_LEDGER_TYPES.includes(typeFilter) ? typeFilter : undefined,
          includeInactive: true,
          dealerId: isOrgWide && dealerFilter ? dealerFilter : undefined,
        },
      })
      .then((res) => {
        setRows(res.data.data)
        setTotalRecords(res.data.totalRecords)
      })
      .catch((err) => setError(err?.response?.data?.message ?? 'Could not load Ledger Master data.'))
      .finally(() => setLoading(false))
  }

  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(load, [typeFilter, pageIndex, dealerFilter])

  // Search box resets to page 0 on every change, debounced - same simple pattern already used
  // elsewhere in this app (DocPrefixMasterPage's SECTION 174 search box).
  useEffect(() => {
    const handle = setTimeout(() => {
      setPageIndex(0)
      load()
    }, 300)
    return () => clearTimeout(handle)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [search])

  const openAdd = () => {
    setEditId(null)
    setForm({ ...EMPTY_FORM, dealerId: isOrgWide ? dealerFilter : '' })
    setFormError(null)
    setMobileWarning(null)
    setShowForm(true)
  }

  const openEdit = (r: LedgerRow) => {
    setEditId(r.id)
    setForm({
      ledgerType: (r.ledgerType as LedgerType) ?? 'Party',
      dealerId: r.dealerId,
      ledgerName: r.ledgerName,
      mobileNumber: r.mobileNumber ?? '',
      alternateMobileNo: r.alternateMobileNo ?? '',
      eMail: r.eMail ?? '',
      address: r.address ?? '',
      pin: r.pin ?? '',
      gstno: r.gstno ?? '',
      pan: r.pan ?? '',
      aadharNumber: r.aadharNumber ?? '',
    })
    setFormError(null)
    setMobileWarning(null)
    setShowForm(true)
  }

  const closeForm = () => {
    setShowForm(false)
    setEditId(null)
    setForm(EMPTY_FORM)
    setFormError(null)
    setMobileWarning(null)
  }

  const checkMobile = (mobile: string) => {
    setMobileWarning(null)
    if (!mobile || mobile.length < 10) return
    staffApi
      .get<boolean>('/api/ledger-master/check-mobile', { params: { mobile, excludeId: editId ?? undefined } })
      .then((res) => {
        if (res.data) setMobileWarning('A ledger with this mobile number already exists.')
      })
      .catch(() => {
        /* best-effort only - never block saving just because this check failed */
      })
  }

  const save = () => {
    const name = form.ledgerName.trim()
    if (!name) {
      setFormError('Ledger Name is required.')
      return
    }
    if (!editId && isOrgWide && !form.dealerId) {
      setFormError('Dealer is required.')
      return
    }
    setSaving(true)
    setFormError(null)

    const payload = {
      ledgerType: form.ledgerType,
      dealerId: isOrgWide ? form.dealerId || null : undefined,
      ledgerName: name,
      mobileNumber: form.mobileNumber.trim() || null,
      alternateMobileNo: form.alternateMobileNo.trim() || null,
      eMail: form.eMail.trim() || null,
      address: form.address.trim() || null,
      pin: form.pin.trim() || null,
      gstno: form.gstno.trim() || null,
      pan: form.pan.trim() || null,
      aadharNumber: form.aadharNumber.trim() || null,
    }

    const req = editId
      ? staffApi.put(`/api/ledger-master/${editId}`, { ...payload, isActive: true })
      : staffApi.post('/api/ledger-master', payload)

    req
      .then(() => {
        closeForm()
        load()
      })
      .catch((err) => setFormError(err?.response?.data?.message ?? 'Could not save this ledger.'))
      .finally(() => setSaving(false))
  }

  const toggleActive = (r: LedgerRow) => {
    const action = r.isActive
      ? staffApi.delete(`/api/ledger-master/${r.id}`)
      : staffApi.put(`/api/ledger-master/${r.id}`, {
          ledgerName: r.ledgerName,
          mobileNumber: r.mobileNumber,
          alternateMobileNo: r.alternateMobileNo,
          eMail: r.eMail,
          address: r.address,
          pin: r.pin,
          gstno: r.gstno,
          pan: r.pan,
          aadharNumber: r.aadharNumber,
          isActive: true,
        })
    action.then(load).catch((err) => setError(err?.response?.data?.message ?? 'Could not update this ledger.'))
  }

  const exportCsv = () => {
    setExporting(true)
    staffApi
      .get<{ data: LedgerRow[]; totalRecords: number }>('/api/ledger-master', {
        params: {
          searchTerm: search || undefined,
          pageIndex: 0,
          pageSize: EXPORT_MAX_ROWS,
          ledgerType: typeFilter && LOCAL_LEDGER_TYPES.includes(typeFilter) ? typeFilter : undefined,
          includeInactive: true,
          dealerId: isOrgWide && dealerFilter ? dealerFilter : undefined,
        },
      })
      .then((res) => {
        const headers = ['Ledger Code', 'Ledger Type', 'Ledger Name', 'Dealer', 'Mobile No', 'Alternate Mobile No', 'Email', 'Address', 'Pin', 'GSTIN', 'PAN', 'Aadhaar No', 'Status']
        const lines = [headers.join(',')]
        for (const r of res.data.data) {
          lines.push([
            csvCell(r.ledgerCode), csvCell(r.ledgerType), csvCell(r.ledgerName), csvCell(r.dealerName),
            csvCell(r.mobileNumber), csvCell(r.alternateMobileNo), csvCell(r.eMail), csvCell(r.address),
            csvCell(r.pin), csvCell(r.gstno), csvCell(r.pan), csvCell(r.aadharNumber),
            csvCell(r.isActive ? 'Active' : 'Deactivated'),
          ].join(','))
        }
        const blob = new Blob([lines.join('\n')], { type: 'text/csv;charset=utf-8;' })
        const url = URL.createObjectURL(blob)
        const link = document.createElement('a')
        link.href = url
        link.download = 'LedgerList.csv'
        link.click()
        URL.revokeObjectURL(url)
      })
      .catch((err) => setError(err?.response?.data?.message ?? 'Could not export ledgers.'))
      .finally(() => setExporting(false))
  }

  const totalPages = Math.max(1, Math.ceil(totalRecords / PAGE_SIZE))
  const isErpType = typeFilter && ERP_SOURCED_TYPES.includes(typeFilter)

  return (
    <div>
      <style>{LEDGER_STYLES}</style>

      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', flexWrap: 'wrap', gap: 12, marginBottom: 4 }}>
        <div>
          <h2 style={PAGE_TITLE_STYLE}>Ledger Master</h2>
          <p style={PAGE_SUBTITLE_STYLE}>Party &amp; Insurance ledgers - Company/Dealer come from the ERP (see note below).</p>
        </div>
      </div>

      <div className="ledger-filters-row" style={{ marginTop: 16 }}>
        {isOrgWide && (
          <div className="ledger-filter-field">
            <label htmlFor="ledger-dealer-filter">Dealer</label>
            <select id="ledger-dealer-filter" value={dealerFilter} onChange={(e) => { setDealerFilter(e.target.value); setPageIndex(0) }}>
              <option value="">All Dealers</option>
              {dealers.map((d) => (
                <option key={d.id} value={d.id}>{d.name}</option>
              ))}
            </select>
          </div>
        )}
        <div className="ledger-filter-field">
          <label htmlFor="ledger-type-filter">Ledger Type</label>
          <select id="ledger-type-filter" value={typeFilter} onChange={(e) => { setTypeFilter(e.target.value as LedgerType | ''); setPageIndex(0) }}>
            <option value="">All</option>
            {ALL_LEDGER_TYPES.map((t) => (
              <option key={t} value={t}>{t}</option>
            ))}
          </select>
        </div>
      </div>

      <div className="ledger-actions-row">
        <div className="ledger-type-tabs">
          {ERP_SOURCED_TYPES.includes(typeFilter as LedgerType) && (
            <span className="ledger-type-tab disabled" title="Coming soon - sourced from the ERP">{typeFilter} (coming soon)</span>
          )}
        </div>
        <div className="ledger-toolbar-right">
          <button className="btn btn-primary" onClick={openAdd}>+ Add</button>
          <button className="ledger-export-btn" title="Export to CSV" disabled={exporting} onClick={exportCsv}>
            {exporting ? '…' : '⭳'}
          </button>
          <input
            className="ledger-search"
            type="text"
            placeholder="Search…"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
        </div>
      </div>

      {isErpType ? (
        <div className="ledger-coming-soon">
          <strong>{typeFilter}</strong> ledgers come live from your ERP (baplfinal, via BaplConnection) - not stored in this table,
          and not browsable here yet. Still pinning down the exact table/query with you - once confirmed, this tab will show the
          real {typeFilter?.toLowerCase()} list.
        </div>
      ) : (
        <>
          {loading && <p className="muted">Loading…</p>}
          {error && <p className="error-text">{error}</p>}

          {!loading && !error && (
            <div className="ledger-table-wrap" style={{ marginBottom: 12 }}>
              {rows.length === 0 ? (
                <p className="muted" style={{ padding: 16, margin: 0 }}>
                  {search || typeFilter || dealerFilter ? 'No ledgers match your search/filter.' : 'No ledgers yet - add one above.'}
                </p>
              ) : (
                <table className="ledger-table">
                  <thead>
                    <tr>
                      <th style={TH_STYLE}>Ledger Code</th>
                      <th style={TH_STYLE}>Type</th>
                      <th style={TH_STYLE}>Name</th>
                      {isOrgWide && <th style={TH_STYLE}>Dealer</th>}
                      <th style={TH_STYLE}>Mobile</th>
                      <th style={TH_STYLE}>Email</th>
                      <th style={TH_STYLE}>GSTIN / PAN</th>
                      <th style={TH_STYLE}>Status</th>
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                    {rows.map((r) => (
                      <tr key={r.id} style={r.isActive ? undefined : { opacity: 0.5 }}>
                        <td data-label="Ledger Code">{r.ledgerCode}</td>
                        <td data-label="Type"><TypeBadge type={r.ledgerType} /></td>
                        <td data-label="Name">{r.ledgerName}</td>
                        {isOrgWide && <td data-label="Dealer">{r.dealerName ?? '-'}</td>}
                        <td data-label="Mobile">{r.mobileNumber ?? '-'}</td>
                        <td data-label="Email">{r.eMail ?? '-'}</td>
                        <td data-label="GSTIN / PAN">{[r.gstno, r.pan].filter(Boolean).join(' / ') || '-'}</td>
                        <td data-label="Status">{r.isActive ? 'Active' : 'Deactivated'}</td>
                        <td data-label="" style={{ whiteSpace: 'nowrap' }}>
                          <button className="btn btn-sm" onClick={() => openEdit(r)}>Edit</button>{' '}
                          <button className="btn btn-sm" onClick={() => toggleActive(r)}>{r.isActive ? 'Deactivate' : 'Reactivate'}</button>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              )}
            </div>
          )}

          {!loading && !error && rows.length > 0 && (
            <div className="ledger-pagination">
              <span>Page {pageIndex + 1} of {totalPages} ({totalRecords} total)</span>
              <button className="btn btn-sm" disabled={pageIndex === 0} onClick={() => setPageIndex((p) => Math.max(0, p - 1))}>Prev</button>
              <button className="btn btn-sm" disabled={pageIndex + 1 >= totalPages} onClick={() => setPageIndex((p) => p + 1)}>Next</button>
            </div>
          )}
        </>
      )}

      {showForm && (
        <div className="card" style={{ marginTop: 20 }}>
          <h3 style={SECTION_TITLE_STYLE}>{editId ? `Edit Ledger - ${form.ledgerType}` : 'Add Ledger'}</h3>
          <div className="ledger-form-grid">
            <label>
              Ledger Type
              <select
                value={form.ledgerType}
                disabled={!!editId}
                onChange={(e) => setForm((f) => ({ ...f, ledgerType: e.target.value as LedgerType }))}
              >
                {LOCAL_LEDGER_TYPES.map((t) => (
                  <option key={t} value={t}>{t}</option>
                ))}
              </select>
            </label>
            {isOrgWide && (
              <label>
                Dealer *
                <select
                  value={form.dealerId}
                  disabled={!!editId}
                  onChange={(e) => setForm((f) => ({ ...f, dealerId: e.target.value }))}
                >
                  <option value="">Select a dealer…</option>
                  {dealers.map((d) => (
                    <option key={d.id} value={d.id}>{d.name}</option>
                  ))}
                </select>
              </label>
            )}
            <label>
              Ledger Name *
              <input value={form.ledgerName} onChange={(e) => setForm((f) => ({ ...f, ledgerName: e.target.value }))} />
            </label>
            <label>
              Mobile No
              <input
                value={form.mobileNumber}
                maxLength={10}
                inputMode="numeric"
                onChange={(e) => setForm((f) => ({ ...f, mobileNumber: e.target.value.replace(/[^0-9]/g, '').slice(0, 10) }))}
                onBlur={(e) => checkMobile(e.target.value)}
              />
            </label>
            <label>
              Alternate Mobile No
              <input
                value={form.alternateMobileNo}
                maxLength={10}
                inputMode="numeric"
                onChange={(e) => setForm((f) => ({ ...f, alternateMobileNo: e.target.value.replace(/[^0-9]/g, '').slice(0, 10) }))}
              />
            </label>
            <label>
              Email
              <input type="email" value={form.eMail} onChange={(e) => setForm((f) => ({ ...f, eMail: e.target.value }))} />
            </label>
            <label>
              Pin Code
              <input
                value={form.pin}
                maxLength={6}
                inputMode="numeric"
                onChange={(e) => setForm((f) => ({ ...f, pin: e.target.value.replace(/[^0-9]/g, '').slice(0, 6) }))}
              />
            </label>
            <label>
              GST No
              <input value={form.gstno} onChange={(e) => setForm((f) => ({ ...f, gstno: e.target.value.toUpperCase() }))} />
            </label>
            <label>
              PAN
              <input value={form.pan} maxLength={10} onChange={(e) => setForm((f) => ({ ...f, pan: e.target.value.toUpperCase() }))} />
            </label>
            <label>
              Aadhaar No
              <input
                value={form.aadharNumber}
                maxLength={12}
                inputMode="numeric"
                onChange={(e) => setForm((f) => ({ ...f, aadharNumber: e.target.value.replace(/[^0-9]/g, '').slice(0, 12) }))}
              />
            </label>
            <label style={{ gridColumn: '1 / -1' }}>
              Address
              <input value={form.address} onChange={(e) => setForm((f) => ({ ...f, address: e.target.value }))} />
            </label>
          </div>
          {mobileWarning && <p className="error-text" style={{ marginTop: 8 }}>{mobileWarning}</p>}
          {formError && <p className="error-text" style={{ marginTop: 8 }}>{formError}</p>}
          <div style={{ display: 'flex', gap: 10, marginTop: 14 }}>
            <button className="btn btn-primary" disabled={saving} onClick={save}>
              {saving ? 'Saving…' : editId ? 'Save changes' : 'Add Ledger'}
            </button>
            <button className="btn" disabled={saving} onClick={closeForm}>Cancel</button>
          </div>
        </div>
      )}
    </div>
  )
}
