using System.ComponentModel.DataAnnotations;

namespace JobCardScanner.Api.Models;

// =====================================================================================
// SECTION 163 (2026-09-30) - "3. Prefix Master" ... "job card number prefix master for Jc , Mt,
// RB for Jc prefix start JC/26-25/0001 then MT/26-25/0001 then RB/26-25/0001".
//
// FACT (confirmed by grep of the real, staged MaterialTransferDocsController.cs and
// RepairBillDocsController.cs this session): Job Card, Material Transfer and Repair Bill document
// numbers are ALL currently generated by ONE shared existing service,
// IJobCardNumberingService/JobCardNumberingService (registered in Program.cs). The actual
// JobCardNumberingService.cs SOURCE FILE is STILL NOT part of this session - it has never been
// pasted/provided - so this table + its API still do NOT drive your REAL Job Card / Material
// Transfer / Repair Bill numbers. Preview below only shows what a number WOULD look like using
// this separate table - paste JobCardNumberingService.cs to actually wire this in.
//
// SECTION 184 (2026-10-02) "in module our sidebar option page name for every page ... Financial
// Year is not required in that none option also add ... Number Length (Padding), Next Number,
// Separator that feilds dont add ... auto increase" - confirmed via AskUserQuestion: Module should
// cover every sidebar page (not just JC/MT/RB), not just those three. This is a REBUILD of the
// SECTION 163/166 shape, not an additive change - renamed DocType -> ModuleKey (see migration SQL
// script backend/add-module-prefix-master-columns.sql, which you must run by hand - I have no DB
// connection and would never run a schema change against your database myself).
//
// ASSUMPTION flagged, not confirmed: ModuleKey's values are meant to be the SAME `key` string
// StaffLayout.tsx's NAV_ITEMS already computes for every sidebar page (navKeyOf(to), e.g.
// 'jobcards', 'repair-bill-new', 'material-transfer-bill', 'dashboard') - I'm reusing that
// existing, already-stable identity rather than inventing a second one. The migration script backfills
// your 3 existing rows as JC -> 'jobcards', MT -> 'material-transfer-bill', RB -> 'repair-bill-new'
// - tell me if any of those three should map to a different page instead (e.g. if Job Card
// numbering should key off '/jobcards/new' specifically rather than the '/jobcards' list page -
// NAV_ITEMS doesn't have a separate nav entry for the wizard route, so 'jobcards' was the closest
// match).
//
// Separator is intentionally NOT a column here (per your "Number Length (Padding), Next Number,
// Separator that feilds dont add" - none of these are meant to be admin-editable form fields) -
// it's a fixed "/" constant in DocPrefixMasterController (SEPARATOR). Padding is likewise not
// stored: the preview/real number format below uses C#'s own "000" numeric format string, which
// auto-expands past 999 to 4 digits, past 9999 to 5 digits, and so on with zero extra code - that's
// what gives you the "after 001-999 auto increase to 4, then 5" behavior you asked for, with
// nothing to configure.
// =====================================================================================

/// <summary>One row per sidebar page/module this app numbers documents for - e.g. the Job Card
/// list page, Material Transfer Bill, Repair Bill - just the prefix text itself (e.g. "JC", or a
/// longer string like "RB/hgh" if you want the separator baked into the prefix text itself - see
/// UsesFinancialYear's doc comment for how that combines with the Financial Year segment).</summary>
public class DocPrefixMaster
{
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>Stable page identity - the same `key` string StaffLayout.tsx's NAV_ITEMS computes
    /// for every sidebar page (navKeyOf(to)), e.g. "jobcards", "repair-bill-new",
    /// "material-transfer-bill". Not an enum/closed list any more (SECTION 184) - any sidebar page
    /// can get a prefix row now, not just JC/MT/RB.</summary>
    [Required, MaxLength(64)]
    public string ModuleKey { get; set; } = default!;

    [Required, MaxLength(20)]
    public string Prefix { get; set; } = default!;

    /// <summary>SECTION 184 ("Financial Year is not required ... none option") - when true (the
    /// default, and the only behavior this table had before SECTION 184), generated numbers are
    /// Prefix/FinancialYear/#### (unchanged). When false ("None" selected for this module), the
    /// Financial Year segment is dropped entirely and numbers are just Prefix/#### - see
    /// DocPrefixMasterController's number-formatting helper for exactly how these two modes
    /// combine with Prefix/Separator.</summary>
    public bool UsesFinancialYear { get; set; } = true;

    public bool IsActive { get; set; } = true;

    public Guid? CreatedById { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public Guid? UpdatedById { get; set; }
    public DateTime? UpdatedAt { get; set; }
}

/// <summary>The running counter per module, per financial year (when that module uses one). Kept
/// as its own table (rather than a column on DocPrefixMaster) so the same prefix can carry a fresh
/// sequence into a new financial year without losing the previous year's last-used number.
/// NOT yet wired to real JC/MT/RB numbering - see class doc comment at the top of this file.</summary>
public class DocNumberSequence
{
    public Guid Id { get; set; } = Guid.NewGuid();

    [Required, MaxLength(64)]
    public string ModuleKey { get; set; } = default!;

    /// <summary>Free-text financial year label, e.g. "26-25" - matches whatever string you want
    /// printed inside the document number, not derived from today's date by this code.
    /// SECTION 184: for a module with UsesFinancialYear=false, this is always stored as "" (empty
    /// string, never null/omitted) - a fixed sentinel so there's exactly one counter row per
    /// FY-less module, rather than leaving this column nullable (SQL Server's handling of multiple
    /// NULLs under a unique index varies by provider/version - an explicit "" sentinel avoids
    /// relying on that).</summary>
    [Required, MaxLength(10)]
    public string FinancialYear { get; set; } = "";

    public int LastSequence { get; set; } = 0;

    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;
}
