using System.ComponentModel.DataAnnotations;

namespace JobCardScanner.Api.Models;

// =====================================================================================
// SECTION 163 (2026-09-30) - "3. Prefix Master" ... "job card number prefix master for Jc , Mt,
// RB for Jc prefix start JC/26-25/0001 then MT/26-25/0001 then RB/26-25/0001".
//
// FACT (confirmed by grep of the real, staged MaterialTransferDocsController.cs and
// RepairBillDocsController.cs this session): Job Card, Material Transfer and Repair Bill document
// numbers are ALL currently generated by ONE shared existing service,
// IJobCardNumberingService/JobCardNumberingService (registered in Program.cs,
// `_numbering.NextMaterialTransferNumberAsync(dealerId)` /
// `_numbering.NextRepairBillNumberAsync(dealerId)` are both called from those two controllers
// already; Job Cards presumably has its own `_numbering.NextJobCardNumberAsync(...)` equivalent
// that this session has not seen). The actual JobCardNumberingService.cs SOURCE FILE is NOT part
// of this session - it has never been pasted/provided - so I cannot see or safely change its
// existing numbering logic without risking breaking Job Card / Material Transfer / Repair Bill
// creation, which are core, already-working features.
//
// DECISION (flagged - Recommendation, not yet applied to live numbering): rather than guess at
// rewriting that shared, unseen service, this table + the read-only preview API
// (DocPrefixMasterController) are built as a SEPARATE, decoupled reference/config store for now.
// It does NOT yet drive the real JC/MT/RB numbers your app prints - those three still come from
// the existing JobCardNumberingService exactly as before. To actually SWITCH live numbering over
// to this table (so real Job Card/Material Transfer/Repair Bill numbers start following whatever
// prefix + sequence you set here), please paste JobCardNumberingService.cs - once I can see its
// current logic, I can safely repoint it at this table instead of maintaining two disconnected
// numbering systems.
//
// ASSUMPTION flagged (financial-year format): your target pattern is JC/26-25/0001. Note this
// differs from a pattern glimpsed earlier this session in mobile/src/screens/
// JobCardWizardScreen.tsx's own displayed example, JC/288/26-27/0006 (which appears to carry an
// extra location/dealer number segment "288", and a different FY string "26-27" vs "26-25"). This
// table stores the FY as a plain string per row (e.g. "26-25") rather than computing it, so
// whatever exact format your dealers actually need can be set explicitly per financial year
// without this code guessing at Indian FY (April-March) rollover rules or a location-number
// segment it hasn't been told about.
//
// Table + read API only (per your answer) - no admin CRUD page. You add/edit rows directly via
// SQL against dbo.DocPrefixMasters / dbo.DocNumberSequences.
// =====================================================================================

/// <summary>One row per document type (JC/MT/RB) - just the prefix text itself, e.g. "JC".</summary>
public class DocPrefixMaster
{
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>"JC", "MT" or "RB" - not an enum so a 4th document type can be added later by
    /// inserting a row, without a code change.</summary>
    [Required, MaxLength(10)]
    public string DocType { get; set; } = default!;

    [Required, MaxLength(10)]
    public string Prefix { get; set; } = default!;

    public bool IsActive { get; set; } = true;

    public Guid? CreatedById { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public Guid? UpdatedById { get; set; }
    public DateTime? UpdatedAt { get; set; }
}

/// <summary>The running counter per document type per financial year. Kept as its own table
/// (rather than a column on DocPrefixMaster) so the same prefix can carry a fresh sequence into a
/// new financial year without losing the previous year's last-used number - see class doc
/// comment's FY-format Assumption for why FinancialYear is a free-text column, not computed.
/// NOT yet wired to real numbering - see class doc comment.</summary>
public class DocNumberSequence
{
    public Guid Id { get; set; } = Guid.NewGuid();

    [Required, MaxLength(10)]
    public string DocType { get; set; } = default!;

    /// <summary>Free-text financial year label, e.g. "26-25" - matches whatever string you want
    /// printed inside the document number, not derived from today's date by this code.</summary>
    [Required, MaxLength(10)]
    public string FinancialYear { get; set; } = default!;

    public int LastSequence { get; set; } = 0;

    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;
}
